inherit_from: .rubocop_todo.yml

inherit_gem:
  bixby: bixby_default.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.4
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'vendor/**/*'

Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'lib/valkyrie/specs/**/*'
    - 'tasks/**/*'
    - 'db/schema.rb'
    - 'Rakefile'
    - '*.gemspec'

RSpec/ExampleLength:
  Enabled: false

Style/FileName:
  Exclude:
    - '**/Gemfile'
    - '**/*.gemspec'
